### ISSUE TITLE
library causing runtime error

### ISSUE THREAD

**Issue by mohammadmahdi255** [hideakitai/ArxTypeTraits#8]
When i include your library in my code it's compile but when I try to run it on Atmega 2560 suddenly board print someof the first char in my setup code
```
delay(2000);
Serial.begin(9600);
Serial.println("Initialize");

eth1 = new DataLinkLayer<HardwareSerial, HardwareSerial>(&Serial1, &Serial, 0xF6, 9600);
eth2 = new DataLinkLayer<HardwareSerial, HardwareSerial>(&Serial2, &Serial, 0xF7, 9600);
eth3 = new DataLinkLayer<HardwareSerial, HardwareSerial>(&Serial3, &Serial, 0xF8, 9600);
eth4 = new DataLinkLayer<SoftwareSerial, HardwareSerial>(&Serial4, &Serial, 0xF9, 9600);

sei(); // Enable interrupts
```
and then restart
even if i'm not calling any of your functions including your library causing the board to stop i select the code i needed from your lib and use it in my code by copy that part but i hope you can find the problem

**Comment by hideakitai** [comment]
Hi, is this a part of implementing this library?

```cpp
DataLinkLayer<HardwareSerial, HardwareSerial>(&Serial1, &Serial, 0xF6, 9600);
```

If so, maybe your usage is not correct. Please give me minimal whole code that can compile and reproduce a problem.

**Comment by mohammadmahdi255** [comment]
no DataLinkLayer is part of my code and it's not from ArxTypeTraits
if you want my full code here is the link to repo:
[https://github.com/mohammadmahdi255/PBFT-Arduino-Client](url)

**Comment by hideakitai** [comment]
I looked in the repositories but could not find where the ArxTypeTraits are being used or how to reproduce the problem.

**Comment by mohammadmahdi255** [comment]
oh
sorry i will make a branch for that

**Comment by mohammadmahdi255** [comment]
i copied some of your code to type.h to solve my problem i will
change the code the way it was

**Comment by mohammadmahdi255** [comment]
i add [ArxTypeTraits](https://github.com/hideakitai/ArxTypeTraits) to data_link.hpp in branch [refactor](https://github.com/mohammadmahdi255/PBFT-Arduino-Client/tree/refactor)
also i compile the code so there is no issue with compile time at my side

**Comment by hideakitai** [comment]
Can this branch be compiled but not working?

**Comment by mohammadmahdi255** [comment]
yes i compile the code
in arduino IDE 2.2.1v

**Comment by hideakitai** [comment]
It looks like you just copy-pasted the part from ArxTypeTraits to Types.h related to is_same, so I'm not sure why that would stop it from working.

I don't have Mega on hand right now, so I can't try it right away. Could you send me the serial console contents when you get it working on both the main branch and the refactor branch?

**Comment by hideakitai** [comment]
I've tried to open and upload your repo to my mega, but it has already been removed. Have you solved this problem?

**Comment by mohammadmahdi255** [comment]
no i'm not resolve it i check my repo and refactor brach still exist

**Comment by mohammadmahdi255** [comment]
this is the link to brach [refactor](https://github.com/mohammadmahdi255/PBFT-Arduino-Client/tree/refactor)

**Comment by hideakitai** [comment]
Thanks, but I couldn't compile it.

```
data_link.hpp:13:10: fatal error: cppQueue.h: No such file or directory
 #include <cppQueue.h>
```

Also, I have tested the following code on Mega. It worked correctly. I think your own code, not this library, causes this issue.

```cpp
#include <ArxTypeTraits.h>

template <typename T>
void say() {
  if (std::is_same<T, int>::value) {
    Serial.println("int");
  } else {
    Serial.println("others");
  }
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);

  delay(5000);

  say<int>();
  say<float>();
}

void loop() {
  // put your main code here, to run repeatedly:

}
```

```
int
others
loop...
loop...
loop...
loop...
```

**Comment by hideakitai** [comment]
Please make an example that can reproduce this problem using only ArxTypeaTraits. If you can, it’s the problem of this library or the usage. If not, the problem is in your own code.

**Comment by hideakitai** [comment]
I found cppQueue.h in https://github.com/SMFSW/Queue/tree/master

And run your refactor branch on Mega. It worked without a runtime error like you mentioned. Maybe this library is not the cause of your error. 

> suddenly board print someof the first char in my setup code and then restart
> even if i'm not calling any of your functions including your library causing the board to stop

This is a log

```
Initialize
ARP REQUEST NIC 0xF6
ARP REQUEST NIC 0xF7
ARP REQUEST NIC 0xF8
ARP REQUEST NIC 0xF9
SEND NIC 0xF6
==============================================================0xf6 0xff 0x04 0x08 0x01 0xf6 0xff 0x7c 0x36 0x0d 0x64 ==============================================================
SEND NIC 0xF7
==============================================================0xf7 0xff 0x04 0x08 0x01 0xf7 0xff 0xe1 0x78 0xa4 0xa9 ==============================================================
SEND NIC 0xF8
==============================================================0xf8 0xff 0x04 0x08 0x01 0xf8 0xff 0xc7 0xa3 0xe7 0xa7 ==============================================================
SEND NIC 0xF9
==============================================================0xf9 0xff 0x04 0x08 0x01 0xf9 0xff 0x5a 0xed 0x4e 0x6a ==============================================================

```

If you still need help after making the following example, please feel free to reopen this issue.

> Please make an example that can reproduce this problem using only ArxTypeaTraits. If you can, it’s the problem of this library or the usage. If not, the problem is in your own code.
