### ISSUE TITLE
is_base_of_v

### ISSUE THREAD

**Issue by illegal-instruction-co** [hideakitai/ArxTypeTraits#9]
is_base_of_v is not working as expected.

c++ is_base_of_v https://godbolt.org/z/br9PY996W works as expected, but this one doesnt detect its base of child.

**Comment by hideakitai** [comment]
In my test code, it works correctly. 

```c++
#include "../ArxTypeTraits.h"
#include <iostream>

class Base {};
class Derived : public Base {};
class Other {};

int main()
{
    std::cout << arx::stdx::is_base_of<Base, Derived>::value << std::endl;
    std::cout << arx::stdx::is_base_of_v<Base, Derived> << std::endl;
    std::cout << arx::stdx::is_base_of_v<Base, Other> << std::endl;
    return 0;
}
```

```shell
$ g++ --std=c++17 test.cpp -o test
$ ./test 
1
1
0
```

**Comment by hideakitai** [comment]
~~But it should be available if C++17 is not enabled...~~ Ah, it's difficult because `inline constexpr` is not available before C++17

**Comment by illegal-instruction-co** [comment]
> ~But it should be available if C++17 is not enabled...~ Ah, it's difficult because `inline constexpr` is not available before C++17

So which toolchain and std version that we need to use  ?

**Comment by hideakitai** [comment]
is_base_of requires C++11. is_base_of_v requires C++17.

**Comment by illegal-instruction-co** [comment]
https://godbolt.org/z/3v17hY5c8

**Comment by hideakitai** [comment]
Sorry, I couldn't understand what you want to say. I think this code works as expected.

```c++
#include "../ArxTypeTraits.h"
#include <iostream>

template <typename T>
struct Parent {
    virtual T Test() = 0;
};

struct Child : public Parent<int> {
    int Test() { return 1; }
};

int main() {
    Child child;

    if constexpr (arx::stdx::is_base_of_v<Parent<int>, decltype(child)>)
        return child.Test();
    else
        return 0;
}
```

```
$ g++ test.cpp --std=c++17 -o test
$ ./test 
$ echo $?
1
```

https://wandbox.org/permlink/kFOtj9M42HgUx4NK

**Comment by illegal-instruction-co** [comment]
You are not compiling code with avrgcc. its working on gcc because std inherited from original.

**Comment by hideakitai** [comment]
As I showed above, gcc with the standard library returns 1 from the main function (by `child.Test()`). As you pasted, avrgcc without standard library also seems to return 1 by `child.Test()`. I think avrgcc (ArxTypeTraits) works as expected for me.

```
main:
        push r28
        push r29
        rcall .
        in r28,__SP_L__
        in r29,__SP_H__
.L__stack_usage = 4
        ldi r24,lo8(vtable for Child+4)
        ldi r25,hi8(vtable for Child+4)
        std Y+2,r25
        std Y+1,r24
        mov r24,r28
        mov r25,r29
        adiw r24,1
        rcall Child::Test()
        nop
        pop __tmp_reg__
        pop __tmp_reg__
        pop r29
        pop r28
        ret
vtable for Child:
        .word   0
        .word   0
        .word   gs(Child::Test())
```

For example, by swapping the definitions of `true_type` and `false_type` from

```c++
    using true_type = integral_constant<bool, true>;
    using false_type = integral_constant<bool, false>;
```

to 

```c++
    using true_type = integral_constant<bool, false>;
    using false_type = integral_constant<bool, true>;
```

It causes returning 48 as expected.

```
main:
        push r28
        push r29
        rcall .
        in r28,__SP_L__
        in r29,__SP_H__
.L__stack_usage = 4
        ldi r24,lo8(vtable for Child+4)
        ldi r25,hi8(vtable for Child+4)
        std Y+2,r25
        std Y+1,r24
        ldi r24,lo8(48)
        ldi r25,0
        pop __tmp_reg__
        pop __tmp_reg__
        pop r29
        pop r28
        ret
vtable for Child:
        .word   0
        .word   0
        .word   gs(Child::Test())
```

**Comment by hideakitai** [comment]
So I needed help understanding what is the problem. I think the `is_base_of` of ArxTypeTraits works as expected for me. Could you tell me more details?

- What is the expected result?
- What is the unexpected result?
- What is my misunderstanding?

**Comment by hideakitai** [comment]
@illegal-instruction-co  I had a chance to use Arduino Uno and tried to test the behavior of is_base_of in practice. The results are as expected for me, but what about you?

```
Child is a child of Parent<int>: 1
```

```c++
#include <ArxTypeTraits.h>

template <typename T>
struct Parent {
    virtual T Test() = 0;
};

struct Child : public Parent<int> {
    int Test() { return 1; }
};

void setup() {
    Serial.begin(115200);
    delay(2000);

    Child child;

    if (std::is_base_of<Parent<int>, decltype(child)>::value) {
        Serial.print("Child is a child of Parent<int>: ");
        Serial.println(child.Test());
    } else {
        Serial.println("Child is NOT a child of Parent<int>");
    }
}

void loop() {}
```

**Comment by illegal-instruction-co** [comment]
Ill check it again and let you know, but it didnt worked for me as expected before. Maybe about my use case.

**Comment by hideakitai** [comment]
If you still need help, please feel free to reopen this issue.
